from PyQt5 import QtCore, QtGui, QtWidgets


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lastversion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1420, 899)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1420, 899))
        MainWindow.setMaximumSize(QtCore.QSize(1420, 899))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("background-color: rgb(49, 49, 49);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 28, 93, 871))
        self.frame.setStyleSheet("background-color: rgb(36, 37, 39);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Collections_button = QtWidgets.QPushButton(self.frame)
        self.Collections_button.setEnabled(True)
        self.Collections_button.setGeometry(QtCore.QRect(14, 170, 65, 65))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Collections_button.sizePolicy().hasHeightForWidth())
        self.Collections_button.setSizePolicy(sizePolicy)
        self.Collections_button.setAutoFillBackground(False)
        self.Collections_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(123, 115, 27);\n"
"    border-radius: 32px;\n"
"}\n"
"")
        self.Collections_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/Collections.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Collections_button.setIcon(icon)
        self.Collections_button.setIconSize(QtCore.QSize(35, 35))
        self.Collections_button.setProperty("border-radius: 50%;", "")
        self.Collections_button.setObjectName("Collections_button")
        self.Callendar_button = QtWidgets.QPushButton(self.frame)
        self.Callendar_button.setGeometry(QtCore.QRect(14, 403, 65, 65))
        self.Callendar_button.setAutoFillBackground(False)
        self.Callendar_button.setStyleSheet("background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        self.Callendar_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/UPDATE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Callendar_button.setIcon(icon1)
        self.Callendar_button.setIconSize(QtCore.QSize(45, 45))
        self.Callendar_button.setObjectName("Callendar_button")
        self.Settings_button = QtWidgets.QPushButton(self.frame)
        self.Settings_button.setGeometry(QtCore.QRect(14, 637, 65, 65))
        self.Settings_button.setAutoFillBackground(False)
        self.Settings_button.setStyleSheet("background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;\n"
"\n"
"")
        self.Settings_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/Settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings_button.setIcon(icon2)
        self.Settings_button.setIconSize(QtCore.QSize(35, 35))
        self.Settings_button.setObjectName("Settings_button")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(93, 26, 2, 1083))
        self.frame_2.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(-60, 25, 1491, 3))
        self.frame_3.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.AddCollection = QtWidgets.QPushButton(self.centralwidget)
        self.AddCollection.setGeometry(QtCore.QRect(1340, 810, 65, 65))
        self.AddCollection.setAutoFillBackground(False)
        self.AddCollection.setStyleSheet("background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        self.AddCollection.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/AddCollection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddCollection.setIcon(icon3)
        self.AddCollection.setIconSize(QtCore.QSize(55, 55))
        self.AddCollection.setObjectName("AddCollection")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1431, 25))
        self.frame_4.setStyleSheet("background-color: rgb(36, 37, 39);\n"
"color: rgb(36, 37, 39);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Close_button = QtWidgets.QPushButton(self.frame_4)
        self.Close_button.setGeometry(QtCore.QRect(1380, 0, 40, 25))
        self.Close_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-style: hidden;\n"
"    border-width: 2px;\n"
"    border-color: rgb(49, 49, 49);\n"
"    background-color: rgb(49, 49, 49);\n"
"}")
        self.Close_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_button.setIcon(icon4)
        self.Close_button.setIconSize(QtCore.QSize(18, 17))
        self.Close_button.setObjectName("Close_button")
        self.line_button = QtWidgets.QPushButton(self.frame_4)
        self.line_button.setGeometry(QtCore.QRect(1340, 0, 40, 25))
        self.line_button.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    border-style: hidden;\n"
"    border-width: 2px;\n"
"    border-color: rgb(49, 49, 49);\n"
"    background-color: rgb(49, 49, 49);\n"
"}")
        self.line_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/Line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.line_button.setIcon(icon5)
        self.line_button.setIconSize(QtCore.QSize(18, 17))
        self.line_button.setObjectName("line_button")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 3, 111, 21))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/gosha/PycharmProjects/Just Notes/Source/Name.png"))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 859, 231, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(36, 37, 39);font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.NoteTitle_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.NoteTitle_5.setGeometry(QtCore.QRect(110, 810, 231, 41))
        self.NoteTitle_5.setStyleSheet("text-align: center;\n"
"font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;\n"
"background-color: rgb(49, 49, 49);\n"
"text-decorations: none;\n"
"border-style:none ;")
        self.NoteTitle_5.setObjectName("NoteTitle_5")
        self.NoteText_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.NoteText_5.setGeometry(QtCore.QRect(360, 810, 951, 41))
        self.NoteText_5.setStyleSheet("text-align: center;\n"
"font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;\n"
"background-color: rgb(49, 49, 49);\n"
"text-decorations: none;\n"
"border-style:none ;")
        self.NoteText_5.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.NoteText_5.setObjectName("NoteText_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(360, 860, 951, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(36, 37, 39);font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(93, 800, 1491, 3))
        self.frame_5.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(96, 28, 1324, 772))
        self.scrollArea.setStyleSheet("QScrollBar:vertical {\n"
                                      "    border: none;\n"
                                      "    background: rgb(49, 49, 49);\n"
                                      "    width: 14px;\n"
                                      "    margin: 15px 0 15px 0;\n"
                                      "    border-radius: 0px;\n"
                                      " }\n"
                                      "\n"
                                      "/*  HANDLE BAR VERTICAL */\n"
                                      "QScrollBar::handle:vertical {    \n"
                                      "    background-color: rgb(123, 115, 27);\n"
                                      "    min-height: 30px;\n"
                                      "    border-radius: 7px;\n"
                                      "}\n"
                                      "\n"
                                      "/* BTN TOP - SCROLLBAR */\n"
                                      "QScrollBar::sub-line:vertical {\n"
                                      "    border: none;\n"
                                      "    background-color: rgb(123, 115, 27);\n"
                                      "    height: 15px;\n"
                                      "    border-top-left-radius: 7px;\n"
                                      "    border-top-right-radius: 7px;\n"
                                      "    subcontrol-position: top;\n"
                                      "    subcontrol-origin: margin;\n"
                                      "}\n"
                                      "QScrollBar::sub-line:vertical:hover {    \n"
                                      "    background-color: rgb(123, 115, 27);\n"
                                      "}\n"
                                      "QScrollBar::sub-line:vertical:pressed {    \n"
                                      "    background-color:rgb(123, 115, 27);\n"
                                      "}\n"
                                      "\n"
                                      "/* BTN BOTTOM - SCROLLBAR */\n"
                                      "QScrollBar::add-line:vertical {\n"
                                      "    border: none;\n"
                                      "    background-color: rgb(123, 115, 27);\n"
                                      "    height: 15px;\n"
                                      "    border-bottom-left-radius: 7px;\n"
                                      "    border-bottom-right-radius: 7px;\n"
                                      "    subcontrol-position: bottom;\n"
                                      "    subcontrol-origin: margin;\n"
                                      "}\n"
                                      "QScrollBar::add-line:vertical:hover {    \n"
                                      "    background-color: rgb(123, 115, 27);\n"
                                      "}\n"
                                      "QScrollBar::add-line:vertical:pressed {    \n"
                                      "    background-color: rgb(123, 115, 27);\n"
                                      "}\n"
                                      "\n"
                                      "/* RESET ARROW */\n"
                                      "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
                                      "    background: none;\n"
                                      "}\n"
                                      "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                      "    background: none;\n"
                                      "}\n"
                                      "\n"
                                      "\n"
                                      "\n"
                                      "")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1301, 759))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.AddCollection.raise_()
        self.lineEdit.raise_()
        self.NoteTitle_5.raise_()
        self.NoteText_5.raise_()
        self.lineEdit_2.raise_()
        self.frame_5.raise_()
        self.scrollArea.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Just Notes"))
        self.NoteTitle_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Myriad Pro\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Title</span></p></body></html>"))
        self.NoteText_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Myriad Pro\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Text</span></p></body></html>"))

