# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetNote.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 61)
        self.NoteFrame_3 = QtWidgets.QFrame(Form)
        self.NoteFrame_3.setGeometry(QtCore.QRect(0, 0, 1279, 61))
        self.NoteFrame_3.setMinimumSize(QtCore.QSize(1240, 61))
        self.NoteFrame_3.setMaximumSize(QtCore.QSize(1281, 61))
        self.NoteFrame_3.setStyleSheet("background-color: rgb(36, 37, 39);\n"
"border-style:solid ;\n"
"    border-width: 2px;\n"
"    border-color: rgb(123, 115, 27);\n"
"border-radius: 15px;")
        self.NoteFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NoteFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NoteFrame_3.setObjectName("NoteFrame_3")
        self.NoteTitle_7 = QtWidgets.QTextBrowser(self.NoteFrame_3)
        self.NoteTitle_7.setGeometry(QtCore.QRect(50, 10, 191, 41))
        self.NoteTitle_7.setStyleSheet("text-align: center;\n"
"font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;\n"
"background-color: rgb(36, 37, 39);\n"
"text-decorations: none;\n"
"border-style:none ;")
        self.NoteTitle_7.setObjectName("NoteTitle_7")
        self.NoteText_7 = QtWidgets.QTextBrowser(self.NoteFrame_3)
        self.NoteText_7.setGeometry(QtCore.QRect(260, 10, 871, 41))
        self.NoteText_7.setStyleSheet("text-align: center;\n"
"font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;\n"
"background-color: rgb(36, 37, 39);\n"
"text-decorations: none;\n"
"border-style:none ;")
        self.NoteText_7.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.NoteText_7.setObjectName("NoteText_7")
        self.DateText_6 = QtWidgets.QTextBrowser(self.NoteFrame_3)
        self.DateText_6.setGeometry(QtCore.QRect(1130, 10, 145, 41))
        self.DateText_6.setStyleSheet("text-align: center;\n"
"font-family: Myriad Pro;\n"
"color: rgb(123, 115, 27);\n"
"font-size:25px;;\n"
"background-color: rgb(36, 37, 39);\n"
"text-decorations: none;\n"
"border-style:none ;")
        self.DateText_6.setObjectName("DateText_6")
        self.checkBox_3 = QtWidgets.QCheckBox(self.NoteFrame_3)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 22, 16, 16))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.NoteTitle_7.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Myriad Pro\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Title</span></p></body></html>"))
        self.NoteText_7.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Myriad Pro\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Note</span></p></body></html>"))
        self.DateText_6.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Myriad Pro\'; font-size:25px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Tahoma\'; font-size:16pt;\">Date</span></p></body></html>"))
