from PyQt5 import QtCore, QtGui, QtWidgets


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lastversion.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1510, 899)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1510, 899))
        MainWindow.setMaximumSize(QtCore.QSize(1510, 899))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet(u"background-color: rgb(49, 49, 49);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QtCore.QRect(0, 28, 93, 871))
        self.frame.setStyleSheet(u"background-color: rgb(36, 37, 39);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)


        self.Show_tasks = QtWidgets.QPushButton(self.frame)
        self.Show_tasks.setObjectName(u"Show_tasks")
        self.Show_tasks.setEnabled(True)
        self.Show_tasks.setGeometry(QtCore.QRect(14, 145, 65, 65))
        sizePolicy1 = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.Show_tasks.sizePolicy().hasHeightForWidth())
        self.Show_tasks.setSizePolicy(sizePolicy1)
        self.Show_tasks.setAutoFillBackground(False)
        self.Show_tasks.setStyleSheet(u"QPushButton{\n"
"	background-color: rgb(123, 115, 27);\n"
"	border-radius: 32px;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Collections", QtCore.QSize(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_tasks.setIcon(icon)
        self.Show_tasks.setIconSize(QtCore.QSize(35, 35))

        #1430

        self.Show_car = QtWidgets.QPushButton(self.centralwidget)
        self.Show_car.setObjectName(u"Filter")
        self.Show_car.setGeometry(QtCore.QRect(1430, 73, 65, 65))
        self.Show_car.setAutoFillBackground(False)
        self.Show_car.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
                                  "border-radius: 32px;")
        icon3 = QtGui.QIcon()
        icon3.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Car.png", QtCore.QSize(),
                      QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_car.setIcon(icon3)
        self.Show_car.setIconSize(QtCore.QSize(45, 45))

        self.Show_car_brand = QtWidgets.QPushButton(self.centralwidget)
        self.Show_car_brand.setObjectName(u"Filter")
        self.Show_car_brand.setGeometry(QtCore.QRect(1430, 173, 65, 65))
        self.Show_car_brand.setAutoFillBackground(False)
        self.Show_car_brand.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
                                    "border-radius: 32px;")
        icon3 = QtGui.QIcon()
        icon3.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Brand.png", QtCore.QSize(),
                      QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_car_brand.setIcon(icon3)
        self.Show_car_brand.setIconSize(QtCore.QSize(45, 45))

        self.Show_model_data = QtWidgets.QPushButton(self.centralwidget)
        self.Show_model_data.setObjectName(u"Filter")
        self.Show_model_data.setGeometry(QtCore.QRect(1430, 273, 65, 65))
        self.Show_model_data.setAutoFillBackground(False)
        self.Show_model_data.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
                                          "border-radius: 32px;")
        icon3 = QtGui.QIcon()
        icon3.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Model.png", QtCore.QSize(),
                      QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_model_data.setIcon(icon3)
        self.Show_model_data.setIconSize(QtCore.QSize(45, 45))

        self.Show_parts = QtWidgets.QPushButton(self.centralwidget)
        self.Show_parts.setObjectName(u"Filter")
        self.Show_parts.setGeometry(QtCore.QRect(1430, 373, 65, 65))
        self.Show_parts.setAutoFillBackground(False)
        self.Show_parts.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
                                           "border-radius: 32px;")
        icon3 = QtGui.QIcon()
        icon3.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Parts.png", QtCore.QSize(),
                      QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_parts.setIcon(icon3)
        self.Show_parts.setIconSize(QtCore.QSize(45, 45))

        self.Show_service = QtWidgets.QPushButton(self.frame)
        self.Show_service.setObjectName(u"Refresh")
        self.Show_service.setEnabled(True)
        self.Show_service.setGeometry(QtCore.QRect(14, 45, 65, 65))
        self.Show_service.setSizePolicy(sizePolicy1)
        self.Show_service.setAutoFillBackground(False)
        self.Show_service.setStyleSheet(u"QPushButton{\n"
                                      "	background-color: rgb(123, 115, 27);\n"
                                      "	border-radius: 32px;\n"
                                      "}\n"
                                      "")
        icon = QtGui.QIcon()
        icon.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Service.png", QtCore.QSize(),
                     QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_service.setIcon(icon)
        self.Show_service.setIconSize(QtCore.QSize(45, 45))


        self.Show_employee = QtWidgets.QPushButton(self.frame)
        self.Show_employee.setObjectName(u"Show_employee")
        self.Show_employee.setGeometry(QtCore.QRect(14, 245, 65, 65))
        self.Show_employee.setAutoFillBackground(False)
        self.Show_employee.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        icon8 = QtGui.QIcon()
        icon8.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Clients.png", QtCore.QSize(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_employee.setIcon(icon8)
        self.Show_employee.setIconSize(QtCore.QSize(45, 45))
        self.Settings_button = QtWidgets.QPushButton(self.frame)
        self.Settings_button.setObjectName(u"Settings_button")
        self.Settings_button.setGeometry(QtCore.QRect(14, 780, 65, 65))
        self.Settings_button.setAutoFillBackground(False)
        self.Settings_button.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Profile.png", QtCore.QSize(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings_button.setIcon(icon2)
        self.Settings_button.setIconSize(QtCore.QSize(35, 35))
        self.Show_clients = QtWidgets.QPushButton(self.frame)
        self.Show_clients.setObjectName(u"Show_clients")
        self.Show_clients.setGeometry(QtCore.QRect(14, 345, 65, 65))
        self.Show_clients.setAutoFillBackground(False)
        self.Show_clients.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        self.Show_clients.setIcon(icon8)
        self.Show_clients.setIconSize(QtCore.QSize(45, 45))
        icon7 = QtGui.QIcon()
        icon7.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Employee.png", QtCore.QSize(),
                      QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Show_clients.setIcon(icon7)
        self.Show_clients.setIconSize(QtCore.QSize(45, 45))
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QtCore.QRect(93, 26, 2, 1083))
        self.frame_2.setStyleSheet(u"background-color: rgb(16, 16, 16);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QtCore.QRect(-60, 25, 1571, 3))
        self.frame_3.setStyleSheet(u"background-color: rgb(16, 16, 16);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Filter = QtWidgets.QPushButton(self.centralwidget)
        self.Filter.setObjectName(u"Filter")
        self.Filter.setGeometry(QtCore.QRect(1430, 808, 65, 65))
        self.Filter.setAutoFillBackground(False)
        self.Filter.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        icon3 = QtGui.QIcon()
        icon3.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Settings.png", QtCore.QSize(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Filter.setIcon(icon3)
        self.Filter.setIconSize(QtCore.QSize(45, 45))
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1511, 25))
        self.frame_4.setStyleSheet(u"background-color: rgb(36, 37, 39);\n"
"color: rgb(36, 37, 39);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Close_button = QtWidgets.QPushButton(self.frame_4)
        self.Close_button.setObjectName(u"Close_button")
        self.Close_button.setGeometry(QtCore.QRect(1470, 0, 40, 25))
        self.Close_button.setStyleSheet(u"QPushButton{\n"
"	border: none;\n"
"	background: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"	border-style: hidden;\n"
"    border-width: 2px;\n"
"    border-color: rgb(49, 49, 49);\n"
"	background-color: rgb(49, 49, 49);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Close.png", QtCore.QSize(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_button.setIcon(icon4)
        self.Close_button.setIconSize(QtCore.QSize(18, 17))
        self.line_button = QtWidgets.QPushButton(self.frame_4)
        self.line_button.setObjectName(u"line_button")
        self.line_button.setGeometry(QtCore.QRect(1430, 0, 40, 25))
        self.line_button.setStyleSheet(u"QPushButton{\n"
"	border: none;\n"
"	background: transparent;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"	border-style: hidden;\n"
"    border-width: 2px;\n"
"    border-color: rgb(49, 49, 49);\n"
"	background-color: rgb(49, 49, 49);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Line.png", QtCore.QSize(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.line_button.setIcon(icon5)
        self.line_button.setIconSize(QtCore.QSize(18, 17))
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QtCore.QRect(10, 3, 111, 21))
        self.label.setPixmap(QtGui.QPixmap(u"../../Users/User/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Name.png"))
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QtCore.QRect(100, 30, 1321, 861))
        self.scrollArea.setStyleSheet(u"QScrollBar:vertical {\n"
"	border: none;\n"
"    background: rgb(49, 49, 49);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"	border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {	\n"
"	background-color: rgb(123, 115, 27);\n"
"	min-height: 30px;\n"
"	border-radius: 7px;\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"	border: none;\n"
"	background-color: rgb(123, 115, 27);\n"
"	height: 15px;\n"
"	border-top-left-radius: 7px;\n"
"	border-top-right-radius: 7px;\n"
"	subcontrol-position: top;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {	\n"
"	background-color: rgb(123, 115, 27);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {	\n"
"	background-color:rgb(123, 115, 27);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"	border: none;\n"
"	background-color: rgb(123, 115, 27);\n"
"	height: 15px;\n"
"	border-bottom-left-radius: 7px;\n"
"	border-bottom-right-radius: "
                        "7px;\n"
"	subcontrol-position: bottom;\n"
"	subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {	\n"
"	background-color: rgb(123, 115, 27);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {	\n"
"	background-color: rgb(123, 115, 27);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"	background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"	background: none;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1319, 859))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalSpacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)


        self.horizontalLayout.addLayout(self.verticalLayout)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.Add_task = QtWidgets.QPushButton(self.centralwidget)
        self.Add_task.setObjectName(u"Add_task")
        self.Add_task.setGeometry(QtCore.QRect(1430, 608, 65, 65))
        self.Add_task.setAutoFillBackground(False)
        self.Add_task.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        icon6 = QtGui.QIcon()
        icon6.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/AddCollection.png", QtCore.QSize(),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Add_task.setIcon(icon6)
        self.Add_task.setIconSize(QtCore.QSize(55, 55))
        self.Download = QtWidgets.QPushButton(self.centralwidget)
        self.Download.setObjectName(u"Download")
        self.Download.setGeometry(QtCore.QRect(1430, 708, 65, 65))
        self.Download.setAutoFillBackground(False)
        self.Download.setStyleSheet(u"background-color: rgb(123, 115, 27);\n"
"border-radius: 32px;")
        icon5 = QtGui.QIcon()
        icon5.addFile(u"C:/Users/User/PycharmProjects/JustNotes_for_MIREA/Source/Download.png", QtCore.QSize(),QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Download.setIcon(icon5)
        self.Download.setIconSize(QtCore.QSize(45, 45))
        MainWindow.setCentralWidget(self.centralwidget)
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.Filter.raise_()
        self.scrollArea.raise_()
        self.Add_task.raise_()
        self.Download.raise_()

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtCore.QCoreApplication.translate("MainWindow", u"Just Notes", None))
        self.Show_tasks.setText("")
        self.Show_tasks.setProperty("border-radius: 50%;", "")
        self.Show_employee.setText("")
        self.Settings_button.setText("")
        self.Show_clients.setText("")
        self.Filter.setText("")
        self.Close_button.setText("")
        self.line_button.setText("")
        self.label.setText("")
        self.Add_task.setText("")
        self.Download.setText("")
    # retranslateUi



